org: williamko
service: members-api

frameworkVersion: ">=1.1.0 <2.0.0"

custom:
  settings:
    MEMBERS_TABLE: members

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  environment: ${self:custom.settings}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.MEMBERS_TABLE}

functions:
  createMember:
    handler: api/member.create
    description: Creates a new member.
    events:
      - http: 
          path: /member
          method: post
  getAllMembers:
    handler: api/member.getAllMembers
    description: Gets all members.
    events:
      - http: 
          path: /members
          method: get
  getMember:
    handler: api/member.getMember
    description: Gets a member by id.
    events:
      - http: 
          path: /member/{id}
          method: get
  updateMember:
    handler: api/member.updateMember
    description: Gets and updates a member by id.
    events:
      - http: 
          path: /member/{id}
          method: put
  deleteMember:
    handler: api/member.deleteMember
    description: Deletes a member by id.
    events:
      - http: 
          path: /member/{id}
          method: delete

resources:
  Resources:
    MembersTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"   
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.MEMBERS_TABLE}
